;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsList]
GameplayTagList=(Tag="Cooldown.Attack.Barrage.Earth",DevComment="")
GameplayTagList=(Tag="Cooldown.Dash",DevComment="")
GameplayTagList=(Tag="Data.Damage",DevComment="")
GameplayTagList=(Tag="Debug.Entities.Player",DevComment="")
GameplayTagList=(Tag="Debug.System.Architecture.GameInstance",DevComment="")
GameplayTagList=(Tag="Debug.System.Architecture.GameMode",DevComment="")
GameplayTagList=(Tag="Event.AbilityTriggered",DevComment="")
GameplayTagList=(Tag="GameplayAbilities.AbilityGiven",DevComment="")
GameplayTagList=(Tag="GameplayCue.Attack.Barrage.FireBarrage",DevComment="")
GameplayTagList=(Tag="GameplayCue.Movement.AirDash.Active",DevComment="")
GameplayTagList=(Tag="GameplayEffects.Status.Stamina.Regen",DevComment="")
GameplayTagList=(Tag="Generic.DamageImmune",DevComment="")
GameplayTagList=(Tag="Physics.CanBePickedUp",DevComment="")

