

[/Script/EngineSettings.GameMapsSettings]
EditorStartupMap=/Game/Main/ClassroomPurgatory/ClassroomMainMenu.ClassroomMainMenu
LocalMapOptions=
TransitionMap=None
bUseSplitscreen=True
TwoPlayerSplitscreenLayout=Horizontal
ThreePlayerSplitscreenLayout=FavorTop
FourPlayerSplitscreenLayout=Grid
bOffsetPlayerGamepadIds=False
GameInstanceClass=/Game/Main/ClassroomPurgatory/GI_ClassroomGameInstance.GI_ClassroomGameInstance_C
GameDefaultMap=/Game/Main/ClassroomPurgatory/ClassroomMainMenu.ClassroomMainMenu
ServerDefaultMap=/Engine/Maps/Entry.Entry
GlobalDefaultGameMode=/Script/Engine.GameModeBase
GlobalDefaultServerGameMode=None

[/Script/HardwareTargeting.HardwareTargetingSettings]
TargetedHardwareClass=Desktop
AppliedTargetedHardwareClass=Desktop
DefaultGraphicsPerformance=Maximum
AppliedDefaultGraphicsPerformance=Maximum

[/Script/HardwareTargeting.HardwareTargetingSettings]
TargetedHardwareClass=Desktop
AppliedTargetedHardwareClass=Desktop
DefaultGraphicsPerformance=Maximum
AppliedDefaultGraphicsPerformance=Maximum

[/Script/Engine.Engine]
+ActiveGameNameRedirects=(OldGameName="TP_LightWeightTemplateBP",NewGameName="/Script/TheSandbox")
+ActiveGameNameRedirects=(OldGameName="/Script/TP_LightWeightTemplateBP",NewGameName="/Script/TheSandbox")
NearClipPlane=0.010000

[/Script/Engine.Engine]
+ActiveGameNameRedirects=(OldGameName="TP_BaseTemplateBP",NewGameName="/Script/MyProject5")
+ActiveGameNameRedirects=(OldGameName="/Script/TP_BaseTemplateBP",NewGameName="/Script/MyProject5")
+ActiveGameNameRedirects=(OldGameName="TP_BlankBP",NewGameName="/Script/BaseTemplate")
+ActiveGameNameRedirects=(OldGameName="/Script/TP_BlankBP",NewGameName="/Script/BaseTemplate")
AssetManagerClassName=/Script/TheSandbox.TheSandboxAssetManager

[/Script/AndroidFileServerEditor.AndroidFileServerRuntimeSettings]
bEnablePlugin=True
bAllowNetworkConnection=True
SecurityToken=F8DAD9A645B26A07D26C0FB1603DECD3
bIncludeInShipping=False
bAllowExternalStartInShipping=False
bCompileAFSProject=False
bUseCompression=False
bLogFiles=False
bReportStats=False
ConnectionType=USBOnly
bUseManualIPAddress=False
ManualIPAddress=



[/Script/AndroidFileServerEditor.AndroidFileServerRuntimeSettings]
bEnablePlugin=True
bAllowNetworkConnection=True
SecurityToken=128B8F004295B08E567BE3B9D5163EE4
bIncludeInShipping=False
bAllowExternalStartInShipping=False
bCompileAFSProject=False
bUseCompression=False
bLogFiles=False
bReportStats=False
ConnectionType=USBOnly
bUseManualIPAddress=False
ManualIPAddress=

[/Script/Engine.RendererSettings]
r.AllowStaticLighting=True
r.GenerateMeshDistanceFields=True
r.SkinCache.CompileShaders=True
r.SkinCache.CompileShaders=True
r.SkinCache.CompileShaders=True
r.RayTracing=True
r.RayTracing=True
r.RayTracing=False
r.Shadow.Virtual.Enable=1
r.Nanite=0 # Nanite is unavailable on older GPU feature sets or slow without fast compute.
r.Nanite.ProjectEnabled=False
r.PathTracing=False # Disable path tracing render pathways
r.CustomDepth=3 # You can disable this to save VRAM and perf writing stencil buffers.
r.DefaultFeature.AutoExposure=False # Auto exposure isn't much use without physically based lighting, which we likely won't use.
r.AntiAliasingMethod=5
r.MSAACount=4
r.SupportLocalFogVolumes=False # Disable fog volume permutations.
r.HeterogeneousVolumes=False # Disable expensive volumetric rendering pathways.
r.DefaultFeature.MotionBlur=False # Motion blur adds cost from velocity and post process, and nobody likes it anyway.
r.Lumen.Reflections.HardwareRayTracing.Translucent.Refraction.EnableForProject=False # Disable HWRT.
r.VirtualTextures=False # You can use virtual texturing if you need, but generally it's not needed by default.
r.VT.AnisotropicFiltering=False # Disable Anisotropic Filtering for VTs which has some overhead, which is off anyways.
bEnableVirtualTexturePostProcessing=False # Don't need.
r.DefaultFeature.Bloom=False # Bloom has a little bit of overhead from blurring low mips.
r.Substrate=True
r.Substrate=false # Substrate has high overhead compared to legacy material system, no benefit here.
r.SupportSkyAtmosphere=False # Reduce material permutations, less PSOs & compile time.
r.ForwardShading=True # Very important - Forward shading has considerable perf benefits, but it can vary per scene \ game, so profile it.
r.SupportStationarySkylight=True
r.SupportPointLightWholeSceneShadows=False # Reduce material permutations, less PSOs & compile time.
r.SupportLowQualityLightmaps=True
r.Mobile.EnableStaticAndCSMShadowReceivers=False # Reduce material permutations, less PSOs & compile time.
r.Mobile.AllowDistanceFieldShadows=False # You may want this on since we are paying for DFs anyway, can be cheap soft shadows vs CSM.
r.DBuffer=False # Remove Decal Buffer for prepass, makes decals more expensive but removes overall overhead.
r.DefaultFeature.AmbientOcclusion=False # AO looks pretty so some projects may want it - you can use DFAO, but we min max perf here.
r.DefaultFeature.AmbientOcclusionStaticFraction=False
r.EarlyZPass=0 # Remove Depth Prepass, this has considerable impact on overdraw so be careful, measure for your scene.
r.Refraction.Blur=False
r.AllowOcclusionQueries=False # Disable Occlusion Culling - it's expensive, measure for your scene, some complex scenes will benefit.
r.TextureStreaming=False # No texture streaming, just blast mip0.
r.Mobile.Forward.EnableLocalLights=0 # We don't need local lights, more perf plz.
r.Mobile.EnableMovableLightCSMShaderCulling=False
r.Mobile.SupportsGen4TAA=False # We will not be using TAA
r.Mobile.AntiAliasing=0
r.DynamicGlobalIlluminationMethod=0
r.ReflectionMethod=1

r.RayTracing.RayTracingProxies.ProjectEnabled=True

r.Substrate.ProjectGBufferFormat=0

r.DefaultFeature.AutoExposure.ExtendDefaultLuminanceRange=True
r.DefaultFeature.AutoExposure.ExtendDefaultLuminanceRange=True

r.DefaultFeature.LocalExposure.HighlightContrastScale=0.8
r.DefaultFeature.LocalExposure.HighlightContrastScale=0.8

r.DefaultFeature.LocalExposure.ShadowContrastScale=0.8
r.DefaultFeature.LocalExposure.ShadowContrastScale=0.8

[/Script/WindowsTargetPlatform.WindowsTargetSettings]
DefaultGraphicsRHI=DefaultGraphicsRHI_DX12
DefaultGraphicsRHI=DefaultGraphicsRHI_DX11

[/Script/Engine.PhysicsSettings]
DefaultGravityZ=-2500.000000

[CoreRedirects]
+EnumRedirects=(OldName="/Script/TheSandbox.EInventoryOperationType",ValueChanges=(("AddingToStackm","AddingToStack")))

[/Script/Engine.GameEngine]
+NetDriverDefinitions=(DefName="GameNetDriver",DriverClassName="OnlineSubsystemSteam.SteamNetDriver",DriverClassNameFallback="OnlineSubsystemUtils.IpNetDriver")
 
[OnlineSubsystem]
DefaultPlatformService=Steam
bHasVoiceEnabled=true
 
[OnlineSubsystemSteam]
bEnabled=true
SteamDevAppId=480
	 
	; If using Sessions
	; bInitServerOnClient=true
 
[/Script/OnlineSubsystemSteam.SteamNetDriver]
NetConnectionClassName="OnlineSubsystemSteam.SteamNetConnection"

[Voice]
bEnabled=true

[/Script/Engine.AudioSettings]
VoiPSampleRate=Normal24000Hz